name: CDK Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: | 
         npm install -g aws-cdk@2
         npm install
        

      
        
      - name: Install AWS SDK and Lambda types
        run: |
          npm install aws-sdk
          npm install @types/aws-lambda --save-dev

      - name: Compile TypeScript to JavaScript
        run: npm run build
      

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
